VERSION=$(cat $VERSION_FILE_PATH)
INSTALL_LOCATION=$FLIPPER_INSTALL_LOCATION/$PLUGIN_NAME/$VERSION

echo "Installing $PLUGIN_NAME@$VERSION to $INSTALL_LOCATION"

rm -rf $INSTALL_LOCATION
mkdir -p $INSTALL_LOCATION
tar -xzf $TAR_PATH -C $INSTALL_LOCATION
