
load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-tools/xlr-testing-utils",
    dependencies = [
    ],
    peer_dependencies = [
        "@npm//typescript",
        "@npm//@typescript/vfs"
    ],
    private = True
)