load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-tools/dsl",
    dependencies = [
        "@npm//@player-ui/types",
        "@npm//@player-ui/player",
        "@npm//@types/mkdirp",
        "@npm//chalk",
        "@npm//command-line-application",
        "@npm//fs-extra",
        "@npm//globby",
        "@npm//jsonc-parser",
        "@npm//mkdirp",
        "@npm//react-flatten-children",
        "@npm//react-json-reconciler",
        "@npm//react-merge-refs",
        "@npm//source-map-js",
        "@npm//ts-node",
        "@npm//typescript",
        "@npm//tapable-ts",
        "@npm//dequal",
    ],
    peer_dependencies = [
        "@npm//react",
        "@npm//@types/react",
    ],
)
